### ISSUE TITLE
Panic when PostGIS tries to query a layer that does not exist

### ISSUE THREAD

**Issue by justenPalmer** [terranodo/tegola#78]
Here's the stack trace:

```
Error Getting MVTLayer: Got the following error (ERROR: relation "forest" does not exist (SQLSTATE 42P01)) running this sql (SELECT ST_AsBinary(wkb_geometry) AS wkb_geometry, name, ogc_fid FROM forest WHERE wkb_geometry && ST_MakeEnvelope(7.14111328025595,50.736455131807304,7.163085936502891,50.72254682842935,4326))
2016/08/31 14:25:32 http: multiple response.WriteHeader calls
2016/08/31 14:25:32 http: panic serving [::1]:62868: runtime error: invalid memory address or nil pointer dereference
goroutine 214 [running]:
net/http.(*conn).serve.func1(0xc82019ca00)
    /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x4cc3c0, 0xc8200100c0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/terranodo/tegola/mvt.(*Tile).AddLayers(0xc820155968, 0xc820055880, 0xd, 0xd, 0x0, 0x0)
    /Users/admin/Dev/go/src/github.com/terranodo/tegola/mvt/tile.go:25 +0x514
github.com/terranodo/tegola/server.handleZXY(0xc05ca0, 0xc820355110, 0xc8201b0700)
    /Users/admin/Dev/go/src/github.com/terranodo/tegola/server/handle_zxy.go:135 +0xad5
net/http.HandlerFunc.ServeHTTP(0x63ade0, 0xc05ca0, 0xc820355110, 0xc8201b0700)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
net/http.(*ServeMux).ServeHTTP(0xc82000eb70, 0xc05ca0, 0xc820355110, 0xc8201b0700)
    /usr/local/go/src/net/http/server.go:1910 +0x17d
net/http.serverHandler.ServeHTTP(0xc82007d800, 0xc05ca0, 0xc820355110, 0xc8201b0700)
    /usr/local/go/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82019ca00)
    /usr/local/go/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:2137 +0x44e
```

**Comment by ARolek** [comment]
Tegola now checks for layer details on startup so this panic no longer happens.
